### ISSUE TITLE
Create call dropping data

### ISSUE THREAD

**Issue by dan1229** [thinknimble/tn-models#2]
When using tn-forms, we can create a map of properties to include in a tn-models call to create an object. For example lets say we have the following:

`{nickname: 'test-name', project: '0090ee7e-350e-430f-842a-a83b2f562f22', products: Array(1), productsRef: Array(1)}
`
tn forms creates the above map, and we can use the following code to send it to our backend and create it:

`
async submit() {
    if (!this.productComparisonForm.isValid) {
        return this.productComparisonForm.validate()
    }
    console.log(this.productComparisonForm.value)
    await ProductComparison.api.create(this.productComparisonForm.value).then(() => {
        this.productComparisonForm = new ProductComparisonForm()
    })
},
`

worth noting the console.log printed the data at the top. the above code should call our backend with the same payload as the form however only sends the following:

`{nickname: "test-name", products: ["0673c256-90e4-4b99-a966-d55d5a1689ab"]}`

dropping the "productRef" and "project" field. Weirder so, upon simply renaming the 'project' field in particular will fix this:

`{"nickname":"geiowgoie","tmp":"0090ee7e-350e-430f-842a-a83b2f562f22","products":["0673c256-90e4-4b99-a966-d55d5a1689ab"]}`

**Comment by paribaker** [comment]
`
         import Model, { fields } from '@thinknimble/tn-models'
`
`
        ...

       export default class ProductComparison extends Model {
             static api = ProductComparisonApi.create(ProductComparison)

            static id = new fields.IdField({ readOnly: true })
            static project = new fields.ModelField({ ModelClass: Project, readOnly: true })
            static nickname = new fields.CharField()
           // static products = new fields.ArrayField({ type: UUID, readOnly: true })  // TODO UUID isnt a valid type for this
           static productsRef = new fields.ArrayField({ type: Product, readOnly: true })

  
         }
`
When using an array field here for products you would use

          `new fields.ArrayField({type:new fields.CharField()}`

This is indicating that it is an array of Char values (alternatively)

           `new fields.ArrayField({type:new fields.IdField()} `

In the docs there should be an example of how to use the array field, essentially it requires an initialized class type with a `.clean()` method. In theory you could create a fake field class and just add the clean method
